In [9]:
import numpy as np

In [2]:
heights = np.array([160, 155, 172, 165, 180, 158, 175, 163, 171, 168])

In [3]:
print(heights)

[160 155 172 165 180 158 175 163 171 168]


In [4]:
heights_mean=np.mean(heights)
print(heights_mean)

166.7


In [10]:
heights_max=np.max(heights)
print("max height is", heights_max)

mean height is 180


In [11]:
heights_std=np.std(heights)
print(heights_std)

7.5372408744845085


In [12]:
heights_argmax=np.argmax(heights)
print(heights_argmax)

4


In [13]:
heights_argmin=np.argmin(heights)
print(heights_argmin)

1


In [20]:
heights_argmax=np.argmax(heights)
heights_argmin=np.argmin(heights)
difference_heights=heights[heights_argmax]-heights[heights_argmin]
print(difference_heights)

25


In [23]:
random_heights=np.random.choice(heights,5,replace=False)
print(random_heights)

[165 175 172 171 163]


In [26]:
random_heights_replacement=np.random.choice(heights,5,replace=True)
print(random_heights_replacement)

[172 165 168 163 168]
